### ISSUE TITLE
Instructions aren't quite clear

### ISSUE THREAD

**Issue by peterkos** [nicoleajoy/rose-pine-spotify#1]
Hi!

Really love this theme, however I had some trouble installing it -- in the readme it would be great if it specified that the _theme_ is `Ziro`, and the color scheme is `rose-pine-dawn` or `rose-pine-moon`. 

```bash
spicetify config current_theme Ziro
# either dawn or moon
spicetify config color_scheme rose-pine-dawn
spicetify config color_scheme rose-pine-moon
```

**Comment by nicoleajoy** [comment]
Hello!

That's a great suggestion, thank you! The previous version of the README was a bit more descriptive. I generalized it because it's likely someone will add to the other themes in the future, and not all the color-schemes will be implemented. But I understand it may be a bit confusing.

For example, Dribbblish is another theme that was recently updated. and it currently only has `rose-pine` as an available color-scheme. The Ziro theme has both `rose-pine-dawn` and `rose-pine-moon`, but not `rose-pine`. It's a mix-n-match situation.

Do you think it would be helpful to create a table of the available themes and their corresponding available color-scheme(s)? Something like the following:

| Theme | Available Color Scheme(s) |
| ------------- | ------------- |
| Dribbblish | `rose-pine` |
| Ziro | `rose-pine-dawn`, `rose-pine-moon` |

Or would it be better to update the sample code? Or both?
